version: '3'

services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    volumes:
      - ./docker/mqtt:/app/docker/mqtt:ro
      - ./docker/mqtt/config:/mosquitto/config:ro
      - ./tmp/mqtt:/app/tmp/mqtt:rw
    env_file:
      - ".env"
    networks:
      - soccer

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    # image: analytics-app-image:latest
    volumes:
      - ./deps/frontend:/app/deps/frontend:rw
      - ./docker/frontend:/app/docker/frontend:ro
      - ./tmp:/app/tmp:rw
    ports:
      - 127.0.0.1:8080:80
    env_file:
      - ".env"
    networks:
      - soccer

  web:
    container_name: web
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    # image: analytics-app-image:latest
    volumes:
      - ./:/app:rw
      - ./tmp:/app/tmp:rw
    ports:
      - 127.0.0.1:80:8000
    env_file:
      - ".env"
    networks:
      - soccer

networks:
  soccer:
    driver: bridge
