version: '3'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    # image: analytics-app-image:latest
    volumes:
      - ./:/app:rw
      - ./tmp:/app/tmp:rw
    ports:
      - 127.0.0.1:80:8000
    env_file:
      - ".env"
    networks:
      - soccer

networks:
  soccer:
    driver: bridge
