# Generated by Django 5.1 on 2024-08-22 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField()),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='participant.participant')),
            ],
        ),
    ]
