# Generated by Django 5.1 on 2024-08-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('started', 'Started'), ('done', 'Done')], default='new', max_length=32),
        ),
    ]
