# Generated by Django 5.1 on 2024-08-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0002_participant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='contact',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='email',
            field=models.EmailField(blank=True, max_length=256, null=True),
        ),
    ]
